name: Rodar Bot Promoções

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Rodar bot
        run: python bot.py

      - name: Upload arquivo
        uses: actions/upload-artifact@v4
        with:
          name: promocoes
          path: promocoes.txt
